# Using Python by Jupyter Notebook

Yizhou(Curtis) Chen\
yizhouchen.curtis@gmail.com

In this file, we are going to introduce some fundamental python code via Jupyter Notebook. 

## 1.Hellow World

Like every programming language, we will start from the code "print()"

In [1]:
print("Hello and Welcome to UNILAG Summer Bootcamp 2024!")

Hello and Welcome to UNILAG Summer Bootcamp 2024!


## 2.Variables and Data Types

Explaining how to store information in variables and the basic data types in Python: strings, integers, and floats.

In [2]:
# Strings
name = "John"
print(name)
# When storing strings, you need to use "".

John


In [3]:
# Integers
age = 30
print(age)

# Floating number
height = 5.9
print(height)

# For integres, all we need to do just directly plugin.

30
5.9


## 3.Lists and Dictionaries

Explaining how to store information in variables and the basic data types in Python: strings, integers, and floats.\
PS: In Python, lists are indexed starting from 0. This means that the first element of a list is assigned index 0, following a common programming convention known as "zero-based indexing."

In [4]:
# Lists
colors = ["red", "green", "blue"]
print(colors[0])  # Accessing the first item in the list

red


In [5]:
print(colors[1])

green


In [6]:
print(colors[2])

blue


### 3.1 Dictionaries

In Python, dictionaries are a built-in data structure designed to store key-value pairs. Each key is associated with a value, and you can access the value by referencing its key. This makes dictionaries highly efficient for data retrieval, especially when quick access to specific elements is needed.\
**Key Features**
* **Keys must be unique:** In any given dictionary, each key appears only once.
* **Values can be of any type:** The values in a dictionary can be numbers, strings, lists, or even other dictionaries.
* **Unordered:** Up to Python 3.7, dictionaries were unordered. As of Python 3.7, dictionaries maintain the order of insertion, but their fundamental implementation does not consider the order of elements.
* **Mutable:** Dictionaries are mutable, meaning you can add, modify, or remove key-value pairs after the dictionary is created.

In [38]:
# Method_1 
# Using {} to stor information, and using ':' to link the name of variable.
person_0 = {"name": "Alice", "age": 25, "city":'Washington D.C.'}
print(person["name"])  # Accessing value of key 'name'

Alice


In [13]:
# Method_2
# Applying dinc() function
person_1 = dict(name='Curtis', age=25, city='Edinburgh')
print(person_1["name"])

Curtis


## 4.Control Structures 

Basic control structures in Python for branching and looping.

### If Statements 

In [14]:
if age > 18:
    print("You are an adult.")
else:
    print("You are a minor.")

You are an adult.


### For Loops 

In [15]:
for color in colors:
    print(color)

red
green
blue


## 5.Functions 

How to define and call functions, a cornerstone of modular and maintainable coding.

In [39]:
def describe_person(person):
    # Check if the 'age' key exists and the person is an adult
    if 'age' in person and person['age'] >= 18:
        return f"{person['name']} is an adult."
    else:
        return f"{person['name']} is not an adult."

In [40]:
print(describe_person(person_0))

Alice is an adult.


## 6.Reading and Writing Files 

Demonstrating how to handle file input and output, crucial for many applications.

In [17]:
# Writing to a file
with open("test.txt", "w") as file:
    file.write("Hello, World!")

# Reading from a file
with open("test.txt", "r") as file:
    content = file.read()
    print(content)

Hello, World!


## 7. Error Handing 

Introducing the concept of handling exceptions with try-except blocks.

In [18]:
try:
    # This will raise an error if 'b' is zero
    a = 10 / 0
except ZeroDivisionError:
    print("Division by zero is not allowed.")

Division by zero is not allowed.


## 8.Using Libraries 

Show how to import libraries and use functions from them, for instance, the math library.

In [19]:
import math
print(math.sqrt(16))  # Prints the square root of 16

4.0


In [20]:
math.sqrt(16)
# You will still got the answer, but just not gonna print out

4.0

In [33]:
!pip install jupyter numpy
# Installing the numpy package via pip install
# In Jupyter notebooks, the exclamation mark "! is used to run shell commands from within the notebook cells. 
# This special character tells Jupyter to execute the subsequent string as a command in the system shell, 
rather than as Python code.

In [29]:
import numpy as np

In [30]:
# Create a 2x3 array of random numbers
array = np.random.rand(2, 3)
print(array)

[[0.00654785 0.48295117 0.16660202]
 [0.25921553 0.23368076 0.9844875 ]]


In [31]:
# Perform element-wise multiplication
multiplied_array = array * 10
print(multiplied_array)

# Calculate the mean of all elements
mean_value = np.mean(array)
print("Mean of the array:", mean_value)

[[0.06547854 4.82951175 1.66602016]
 [2.5921553  2.33680761 9.84487502]]
Mean of the array: 0.3555808061796035
